### ISSUE TITLE
Filter sources of Law and Policy when creating / editing regime assessment

### ISSUE THREAD

**Issue by jhung** [fluid-project/lcil#108] opened 2022-11-14 19:20 UTC
When creating or editing a Regime Assessment, the user should be able to filter the sources of law and policy by different regions.

Currently all sources of law and policy are shown and the user needs to scroll through the whole list to find what they need. There should be a way to filter this view so only the results they are interested in are shown.

Exact functionality to be confirmed with IRIS, and designs to be created before implementation.

**Comment by jobara** [comment] 2022-11-15 22:28
Is this a duplicate of #42

**Closed** 2022-12-15 21:35 UTC
Labels: enhancement, mothballed
